[![Review Assignment Due Date](https://classroom.github.com/assets/deadline-readme-button-24ddc0f5d75046c5622901739e7c5dd533143b0c8e959d652212380cedb1ea36.svg)](https://classroom.github.com/a/G801g4IR)
= Gestionnaire de Fichiers en Commandes en Ligne avec Annotations
 

L'objet de ce mini-projet est de développer un https://fr.wikipedia.org/wiki/Gestionnaire_de_fichier[gestionnaire de fichiers] en commande en ligne. Le gestionnaire de fichier s'appuie sur le système de fichier de votre système d'exploitation. Le gestionnaire de fichier doit offrir la possibilité d'annoter les éléments contenus dans un répertoire (i.e.fichiers, répertoires).
Vous devrez respecter les contraintes fonctionnelles et techniques mentionnées ci-dessous.

[IMPORTANT]
====
Vous respecterez les contraintes suivantes:

* Ce mini-projet est à réaliser en Java par groupe de 2 étudiants.
  - les 2 étudiants doivent coopérer à travers un même git. Un des deux étudiants devra permettre à l'autre d'utiliser son git.
* Il devra comporter une documentation dans ce git.
  - La documentation devra décrire l'usage de l'application (_manuel utilisateur_) ainsi que la conception du jeu (_manuel technique_).
  - La documentation doit être un fichier .md ou .adoc et accessible depuis le `git`
* Vous utiliserez `git` en effectuant des commits réguliers comportant des messages informatifs. L'usage des "pull requests" est également fortement conseillé, montrant ainsi votre collaboration au sein du groupe. 
* Le _build_ sera assuré par Maven et plus précisément Maven wrapper (déjà intégré dans le projet).
Aucune manipulation en dehors de Maven ne devra être nécessaire.
* La version de Java à utiliser est la https://adoptium.net/[version 17].
* Le _build_ devra intégrer `checkstyle` pour la vérification des règles de codages Google.
Le projet devra donc les respecter.
`checkstyle` devra être exécuté automatiquement durant la phase `validate` du cycle de vie par défaut.
* Des tests unitaires https://junit.org/junit5/docs/current/user-guide/[JUnit 5] (version https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter/5.9.1[_5.9.1_]) devront être disponibles pour la plupart des méthodes développées.
* Un outil de https://fr.wikipedia.org/wiki/Couverture_de_code[_Code Coverage_] devra être intégré au _build_
* Les fonctionnalités du langage Java devront être utilisées au mieux (POO, exceptions, librairie de collections, I/O, …).
* L'application devra pouvoir être exécutée à partir d'un `jar` incluant toutes les dépendances.
====

== Description du gestionnaire de fichiers
* L'interface proposera une visualisation du contenu d'un répertoire en mode texte. A chaque élément du répertoire (**ER**), on associera un numero (**NER**) permettant de le designer lors de l'utilisation d'une des commandes définies ci-dessous.

* Les actions de l'utilisateur seront saisies au clavier sous la forme `[<NER>] [<commande>] [<nom>]`. Les crochets signifient "optionnel" 
  - Par exemples:
   ** `3 cut` ; efface le troisième fichier.
   ** `3`  ; l'utilisateur désigne le troisième élément du répertoire.
  - Si l'utilisateur ne place pas de NER, c'est le dernier NER utilisé qui sera utilisé pour une commande qui en nécessite. Exemple `visu`
  - Les commandes du gestion de fichiers à implémenter sont:
    - `[<NER>] copy`
    - `paste`  ; si l’élément existe, alors le nom du nouvel élément sera concaténé avec "-copy"
    - `[<NER>] cut`
    - `..` ; pour remonter d'un cran dans le système de fichiers
    - `[<NER>] .` ; pour entrer dans un répertoire à condition que le NER désigne un répertoire. Exemple "4 ."
    - `mkdir <nom>` ; pour créer un répertoire
    - `[<NER>] visu` ; permet de voir le contenu d'un fichier texte. Si le fichier n'est pas de type texte, vous afficherez sa taille.
    - `find <nom fichier>` ; Recherche dans toutes les sous répertoires du répertoire courant, le(s) fichier(s) et les affiches.

* L'application permettra à l'utilisateur d'annoter un ER
  - l'annotation consiste à ajouter ou retirer un texte associé à un ER. 
  - Par exemples:
       ** 3 + "ceci est un texte" ; le texte est ajouté ou concaténé au texte existant sur l'ER
       ** 3 -  ; retire tout le texte associé à l'ER 3

 

== Description de l'application à réaliser

* L'interface proposera une visualisation du répertoire courant en mode texte en quatre parties. La partie:
  . présente le cheminement depuis la racine du système de fichier de votre système de fichier.
  . affiche la note associée à l'élément courant NER si elle existe. L'élément courant correspond à la désignation du NER par l'utilisateur ou désigné dans la dernière commande utilisée. Exemple `3 copy`, 3 devient l'élément courant.
  . affiche les ER du répertoire avec leurs NER
  . présente un prompt invitant l'utilisateur à saisir une des commandes présentées ci-dessus.

* Une interface spécifique pourra être proposée pour des situations particulières (visualiser le contenu d'un fichier, une aide, ...).

* Toutes les notes associées aux éléments du répertoire courant seront stockés dans un seul fichier appelé "notes" dans le répertoire courant. Ce fichier peut contenir des objets "sérialisés" ou d'autres formats.



== Références
* Article Wikipedia https://fr.wikipedia.org/wiki/Gestionnaire_de_fichiers[Gestionnaire de fichiers]

* Quelques bibliothèques :
http://fusesource.github.io/jansi/[JAnsi] (couleur dans un terminal),
https://github.com/jline/jline3[JLine] (gestion des saisies)

== Manuel utilisateur

> À compléter :
> Comment l'utilisateur peut savoir quelle commande taper pour un élément du répertoire désigné ?

il trouvera une liste de commandes en dessous de la liste au début de l'exécution de l'application.

1-  Lancer l'Application : l'utilisateur doit exécuter cette insctruction :

  java -jar target/explorer-1.0-SNAPSHOT-jar-with-dependencies.jar

2-  Sélectionnez l'Élément suivi par la commande souhaité : Pour effectuer une opération sur un élément particulier du répertoire (fichier ou répertoire)  
 
Commandes disponibles

  vous devez utiliser son NER associé à côté de celui-ci suivi par un de ces commande suivant : 

    - Pour copier un élément désigné par le numéro 1 saisissez " 1 copy ".
  
    - Pour coller un élément qui a été Sélectionner pour copier, selectionnez le repertoire apres saisissez "paste".
  
    - Pour voir et lire le contenu d'un fichier texte désigné par le numéro 3 , saisissez "3 visu".
    
    - Pour couper un élément désigné par le numéro 5, saisissez "5 cut". (copier et supprimer le de la liste en meme temps)
    
    - Pour entrer dans un répertoire à condition que le NER désigne un répertoire, saisissez "6 .".
    
    - Pour sortir d'un fichier au fichier precedant , saisissez "7 ..".
    
    - Pour ajouter une note à un élement, saisissez " 8 + "<Note>" ".
     
    - Pour supprimer une note d'un élement, saisissez " 9 - ".
    
    - Pour supprimer un élément désigné par le numéro 10, saisissez "remove 10".
     
    - Pour activer l'auto-complétion, commencez à taper la première lettre de la commande souhaitée, puis appuyez sur la touche TAB.
    
    - pour créer un nouveau répertoire, saisissez "mkdir <nom du répertoire>".
    
    - pour trouver le repertoire d'un élement, saisissez " find <nom du element> ".

3-Quitter l'Application : pour quitter l'Application saisissez 
  
  exit 



> Quelles sont les mises à jours du fichier des annotations à effectuer en fonction des types de commandes ?

    le fichier des annotations sera effectuer seulement avec la commande "+" ou "-" 
    "+": cette commande va ajouter une note dans le fichier des Annotations
    "-": cette commande va supprimer une note dans le fichier des Annotations

> Y a t il des bibliothèques Java qui permettront de prendre en charge la visualisation d'une image png si l'utilisateur veut l'afficher ?

En effet, en Java, il existe des bibliothèques qui permettent de manipuler des images et de les afficher dans le terminal.
----------
Java Advanced Imaging (JAI) est une extension de la plateforme Java 
qui fournit des fonctionnalités avancées pour le traitement d'images. 
Cette bibliothèque offre un ensemble d'outils et de fonctionnalités pour manipuler,
traiter et afficher des images dans des applications Java.
----------
  JDeli est une bibliothèque Java spécialisée dans le traitement et la manipulation d'images,
  offrant une alternative plus performante et flexible aux classes standard Java Image I/O.
----------
> Quelles sont les commandes qui seraient utiles de rajouter ?

   Commandes de suppression. 
   Commandes pour renommer les fichiers.
   Commandes pour ouvrir certain fichier avec l'app souhaité.

> Quelles améliorations peut on envisager pour rendre l'usage de l'interface clavier plus souples/efficaces pour l'utilisateur ?
----------
1. Auto-complétion et suggestions :
Utiliser une bibliothèque comme JLine qui offre des fonctionnalités d'auto-complétion et de suggestions. 
Cela permet à l'utilisateur de naviguer dans les options disponibles en appuyant sur la touche TAB, 
ce qui rend l'interface plus interactive et conviviale.
-----------
2. Historique des commandes :
Intégrer un mécanisme de gestion de l'historique des commandes. 
L'utilisateur peut naviguer dans l'historique (flèches haut/bas) pour revoir et réexécuter les commandes précédentes.
------------
3. Instructions contextuelles :
Fournir des informations contextuelles en temps réel lors de la saisie des commandes. 
Cela peut inclure l'affichage d'aide ou de suggestions en fonction du contexte de la commande en cours de saisie.
------------
4. Gestion des erreurs :
Gérer les erreurs de manière conviviale en fournissant des messages clairs et informatifs pour guider 
l'utilisateur lorsqu'une commande n'est pas reconnue ou lorsqu'une erreur se produit.


> Quelles évolutions peut-on envisager ?
1- Gestion avancée des fichiers : Intégrer des opérations avancées telles que le renommage de fichiers, la compression/décompression.
2- Interface utilisateur améliorée : Implémenter une interface utilisateur plus conviviale et informative en utilisant des menus interactifs, des messages plus clairs pour guider l'utilisateur, ou encore une aide contextuelle pour expliquer les commandes.
3- Options de tri et de filtrage : Ajouter des fonctionnalités de tri et de filtrage pour permettre à l'utilisateur de trier ou filtrer les fichiers en fonction de différents critères comme le nom, la taille, la date, etc.
4- Support de l'édition de fichiers : Intégrer la possibilité d'éditer des fichiers texte directement depuis l'interface en ligne de commande.

== Manuel technique
=== Compiler le projet
.Sous Linux
----
$ ./mvnw package
----

.Sous Windows
----
> mvn -N wrapper:wrapper
> ./mvnw package
----

=== Exécuter l'application
----
$ java -jar target/explorer-1.0-SNAPSHOT-jar-with-dependencies.jar
----

> À compléter :
> Comment consulter le rapport de couverture de code par les tests ?
Après avoir exécuté la commande "mvn test", vous pourrez visualiser le rapport de couverture en ouvrant le fichier index.html situé dans le répertoire target/site/jacoco/index.html dans un navigateur. Cela affichera les pourcentages de couverture des tests.


> Quelles bibliothèques ont été utilisées et pourquoi ?

les bibliothèques que j'ai intégrées sont:

        "java.io" et "java.nio.file" : Ces bibliothèques standard de Java sont utilisées pour la manipulation des fichiers
    et la gestion des répertoires et des chemins.

        "org.apache.commons.io" : Cette bibliothèque est utilisée pour extraire des informations supplémentaires des fichiers,
    telles que les extensions de fichier.
    

          "JAnsi" : Utilisée pour la coloration dans un terminal, 
    cette bibliothèque permet d'ajouter des couleurs et des styles au texte affiché dans un terminal, 
    améliorant ainsi la lisibilité et l'expérience utilisateur.

          "JLine" : Cette bibliothèque est spécifiquement utilisée pour la gestion des saisies dans le terminal. 
    Elle offre des fonctionnalités avancées pour gérer les entrées utilisateur, 
    la complétion automatique et d'autres interactions pour faciliter l'utilisation de l'interface en ligne de commande.

    
> Quel est le rôle des différentes classes ?

App.java : lancement d'application et contient les variables du programme.
ConsoleColors.java : Contient les couleurs d'application.
CopyPaste.java : copier et couper et coller un element.
CsvReader.java : lire et afficher les notes.
DeleteFunction.java : supprimer un element.
DirectoryFunction.java : créer un répertoire
Element.java : contient les elements de la liste.
FileFunctions.java : trouver le chemin d'un fichier.
Functions.java : contient des methodes simple pour la fonctionalité d'application.
VisuReader.java : affichier le contenu d'un fichier texte sinon afficher sa taille.

> Quels traitements sont réalisés pour gérer une commande saisie par l'utilisateur ?

le programme met en place un lecteur de ligne à l'aide de la bibliothèque JLine.
Il lit les commandes de l'utilisateur depuis le terminal et découppe 
la commande en parties et traite chaque partie individuelement et 
l'execute jusqua'il termine le traitement.

> Quelles améliorations peut-on envisager ?
1- Gestion avancée des fichiers : Intégrer des opérations avancées telles que le renommage de fichiers, la compression/décompression.
2- Interface utilisateur améliorée : Implémenter une interface utilisateur plus conviviale et informative en utilisant des menus interactifs, des messages plus clairs pour guider l'utilisateur, ou encore une aide contextuelle pour expliquer les commandes.
3- Options de tri et de filtrage : Ajouter des fonctionnalités de tri et de filtrage pour permettre à l'utilisateur de trier ou filtrer les fichiers en fonction de différents critères comme le nom, la taille, la date, etc.
4- Support de l'édition de fichiers : Intégrer la possibilité d'éditer des fichiers texte directement depuis l'interface en ligne de commande.
